#!/usr/bin/env bash
# ==============================================================================
# Auto-Proxy Conflict Resolver for devctl
# Detects host Nginx, Apache, or Caddy and configures seamless upstream routing
# ==============================================================================

set -e

BASE_DOMAIN="${1:-dev-server.suburban.ng}"
INTERNAL_PORT="${2:-8080}"

echo "[*] Inspecting port 80 and 443 bindings on host..."

PORT_80_PROCESS=$(ss -tulpn | grep ':80 ' || true)
PORT_443_PROCESS=$(ss -tulpn | grep ':443 ' || true)

HAS_NGINX=false
HAS_APACHE=false
HAS_STANDALONE_CADDY=false

if echo "$PORT_80_PROCESS" | grep -iq "nginx" || command -v nginx &>/dev/null && systemctl is-active --quiet nginx; then
    HAS_NGINX=true
fi

if echo "$PORT_80_PROCESS" | grep -iq "apache\|httpd" || command -v apache2 &>/dev/null && systemctl is-active --quiet apache2; then
    HAS_APACHE=true
fi

if echo "$PORT_80_PROCESS" | grep -iq "caddy" && ! docker ps --format '{{.Names}}' | grep -q "^caddy$"; then
    HAS_STANDALONE_CADDY=true
fi

if [ "$HAS_NGINX" = true ]; then
    echo "⚡ Detected active Nginx on host."
    echo "   Configuring Nginx reverse-proxy pass to Caddy on port ${INTERNAL_PORT}..."

    NGINX_CONF_DIR="/etc/nginx/conf.d"
    mkdir -p "$NGINX_CONF_DIR"

    cat << EOF > "${NGINX_CONF_DIR}/devctl_${BASE_DOMAIN//./_}.conf"
# Auto-generated by devctl for wildcard routing
server {
    listen 80;
    server_name *.${BASE_DOMAIN} ${BASE_DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:${INTERNAL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
    if nginx -t &>/dev/null; then
        nginx -s reload
        echo "[✓] Nginx reloaded successfully. Routing *."${BASE_DOMAIN}" -> 127.0.0.1:${INTERNAL_PORT}"
    else
        echo "[!] Warning: Nginx syntax test failed. Check /etc/nginx/conf.d/."
    fi

elif [ "$HAS_APACHE" = true ]; then
    echo "⚡ Detected active Apache on host."
    echo "   Configuring Apache proxy pass to Caddy on port ${INTERNAL_PORT}..."

    a2enmod proxy proxy_http proxy_wstunnel 2>/dev/null || true
    APACHE_CONF="/etc/apache2/sites-available/devctl_${BASE_DOMAIN//./_}.conf"

    cat << EOF > "$APACHE_CONF"
<VirtualHost *:80>
    ServerName ${BASE_DOMAIN}
    ServerAlias *.${BASE_DOMAIN}

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:${INTERNAL_PORT}/
    ProxyPassReverse / http://127.0.0.1:${INTERNAL_PORT}/
</VirtualHost>
EOF
    a2ensite "devctl_${BASE_DOMAIN//./_}.conf" 2>/dev/null || true
    systemctl reload apache2 || true
    echo "[✓] Apache reloaded successfully."

else
    echo "[✓] No host reverse proxy conflicts detected. Caddy will bind directly to 80/443."
fi
