"""
Caddy reverse proxy management for devctl.
Manages standard dynamic site configurations under conf.d and reloads Caddy seamlessly.
Caddy automatically provisions individual SSL certificates for each domain without complex on-demand policies.
"""

import subprocess
import json
import urllib.request
import urllib.error
from pathlib import Path
from typing import Dict, List, Any, Optional
from .config import Config, BASE_DIR

CONF_DIR = BASE_DIR / "infra" / "conf.d"
CONF_DIR.mkdir(parents=True, exist_ok=True)


class CaddyManager:
    """Manages Caddy site configurations and reloads."""

    def __init__(self, conf_dir: Optional[Path] = None):
        self.conf_dir = conf_dir or CONF_DIR
        self.conf_dir.mkdir(parents=True, exist_ok=True)

    def reload_caddy(self) -> Dict[str, Any]:
        """Reload Caddy configuration via Docker or API."""
        try:
            res = subprocess.run(
                ["docker", "exec", "caddy", "caddy", "reload", "--config", "/etc/caddy/Caddyfile"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                check=False,
            )
            if res.returncode == 0:
                return {"success": True, "method": "docker_exec"}
        except Exception:
            pass

        # Fallback: Caddy Admin API reload
        try:
            req = urllib.request.Request(
                f"{Config.CADDY_ADMIN_API}/load",
                headers={"Content-Type": "text/caddyfile"},
                data=b"",
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=5) as response:
                return {"success": response.status < 400, "method": "admin_api"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def check_health(self) -> bool:
        """Check if Caddy container is running and healthy."""
        try:
            res = subprocess.run(
                ["docker", "inspect", "--format", "{{.State.Running}}", "caddy"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                check=False,
            )
            return res.stdout.strip().lower() == "true"
        except Exception:
            return False

    def add_route(
        self,
        domain: str,
        upstream_host: str,
        upstream_port: int,
        route_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Create a clean standard Caddy site block and reload Caddy.
        Caddy automatically requests a Let's Encrypt / ZeroSSL certificate for this domain.
        """
        service_slug = domain.split(".")[0].lower()
        conf_file = self.conf_dir / f"{service_slug}.caddy"

        caddy_content = f"""# Auto-generated by devctl for {service_slug}
{domain} {{
    encode zstd gzip

    header {{
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        Referrer-Policy "strict-origin-when-cross-origin"
    }}

    reverse_proxy {upstream_host}:{upstream_port}
}}
"""
        with open(conf_file, "w", encoding="utf-8") as f:
            f.write(caddy_content)

        reload_res = self.reload_caddy()
        return {
            "success": True,
            "domain": domain,
            "conf_file": str(conf_file),
            "reloaded": reload_res.get("success", True),
        }

    def remove_route(self, domain: str, route_id: Optional[str] = None) -> Dict[str, Any]:
        """Delete site config and reload Caddy."""
        service_slug = domain.split(".")[0].lower()
        conf_file = self.conf_dir / f"{service_slug}.caddy"

        if conf_file.exists():
            conf_file.unlink()

        reload_res = self.reload_caddy()
        return {
            "success": True,
            "domain": domain,
            "reloaded": reload_res.get("success", True),
        }

    def list_routes(self) -> List[Dict[str, Any]]:
        """List active configuration snippets."""
        routes = []
        for file in self.conf_dir.glob("*.caddy"):
            routes.append({"file": file.name, "service": file.stem})
        return routes
