"""
Incident Dossier Generator for AI-Ops.
Creates comprehensive markdown documentation for each incident including:
- Error details and stack traces
- Fix branch and commit information
- Code changes (diff)
- Verification results
- Resolution proof
"""

import subprocess
import time
from pathlib import Path
from typing import Dict, Any, Optional
from devctl.core.config import Config


class IncidentDossier:
    """Generates and manages incident resolution dossiers."""

    def __init__(self, incidents_dir: Path):
        self.incidents_dir = incidents_dir
        self.incidents_dir.mkdir(parents=True, exist_ok=True)

    def create_dossier(
        self,
        incident_id: str,
        service_name: str,
        error_category: str,
        error_snippet: str,
        severity: str,
        context: str,
        container_name: Optional[str] = None,
        logs: Optional[str] = None,
    ) -> Path:
        """Create initial incident dossier when incident is detected."""
        dossier_path = self.incidents_dir / f"{incident_id}.md"

        timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())

        content = f"""# Incident Dossier: {incident_id}

## Summary
- **Service**: {service_name}
- **Container**: {container_name or 'unknown'}
- **Severity**: {severity.upper()}
- **Context**: {context}
- **Error Category**: {error_category}
- **Detected**: {timestamp}
- **Status**: 🔴 OPEN

## Error Details

### Error Snippet
```
{error_snippet}
```

### Full Logs (Last 50 Lines)
```
{logs or 'No logs available'}
```

## Resolution

### Fix Branch
_Waiting for OpenCode to create fix branch..._

### Code Changes
_Waiting for fix implementation..._

### Verification Results
_Waiting for verification..._

## Proof of Resolution
_Waiting for fix deployment and verification..._

---
_Generated by AI-Ops Incident Dossier System_
"""

        dossier_path.write_text(content, encoding="utf-8")
        return dossier_path

    def update_dossier_with_fix(
        self,
        incident_id: str,
        fix_branch: str,
        commit_hash: str,
        commit_message: str,
        files_changed: list,
        diff_summary: str,
    ):
        """Update dossier with fix information."""
        dossier_path = self.incidents_dir / f"{incident_id}.md"
        if not dossier_path.exists():
            return

        content = dossier_path.read_text(encoding="utf-8")

        # Replace the "Fix Branch" section
        fix_section = f"""### Fix Branch
- **Branch**: `{fix_branch}`
- **Commit**: `{commit_hash[:12]}`
- **Message**: {commit_message}
- **Files Changed**: {len(files_changed)}
  - {chr(10).join(f'  - `{f}`' for f in files_changed[:10])}

### Code Changes (Diff Summary)
```diff
{diff_summary[:2000]}
```
"""

        content = content.replace(
            "### Fix Branch\n_Waiting for OpenCode to create fix branch..._\n\n### Code Changes\n_Waiting for fix implementation..._",
            fix_section
        )

        dossier_path.write_text(content, encoding="utf-8")

    def update_dossier_with_verification(
        self,
        incident_id: str,
        verification_passed: bool,
        test_results: str,
        deployment_status: str,
    ):
        """Update dossier with verification results."""
        dossier_path = self.incidents_dir / f"{incident_id}.md"
        if not dossier_path.exists():
            return

        content = dossier_path.read_text(encoding="utf-8")

        status_emoji = "✅" if verification_passed else "❌"
        status_text = "PASSED" if verification_passed else "FAILED"

        verification_section = f"""### Verification Results
- **Status**: {status_emoji} {status_text}
- **Deployment**: {deployment_status}
- **Test Results**:
```
{test_results}
```
"""

        content = content.replace(
            "### Verification Results\n_Waiting for verification..._",
            verification_section
        )

        # Update status if verification passed
        if verification_passed:
            content = content.replace(
                "- **Status**: 🔴 OPEN",
                "- **Status**: 🟡 PENDING CONFIRMATION"
            )

        dossier_path.write_text(content, encoding="utf-8")

    def mark_resolved(
        self,
        incident_id: str,
        merged_by: str,
        merge_commit: str,
        production_deployed: bool,
    ):
        """Mark incident as resolved and merged."""
        dossier_path = self.incidents_dir / f"{incident_id}.md"
        if not dossier_path.exists():
            return

        content = dossier_path.read_text(encoding="utf-8")
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())

        # Update status
        content = content.replace(
            "- **Status**: 🟡 PENDING CONFIRMATION",
            f"- **Status**: ✅ RESOLVED & MERGED"
        )
        content = content.replace(
            "- **Status**: 🔴 OPEN",
            f"- **Status**: ✅ RESOLVED & MERGED"
        )

        # Add resolution proof
        proof_section = f"""

## Proof of Resolution

### Merge Information
- **Merged By**: {merged_by}
- **Merge Commit**: `{merge_commit[:12]}`
- **Merged At**: {timestamp}
- **Production Deployed**: {'✅ Yes' if production_deployed else '❌ No'}

### Resolution Summary
The fix has been verified, merged to master, and deployed to production.
All systems are operating normally.

---
_Dossier closed by AI-Ops Incident Resolution System_
"""

        content = content.replace(
            "---\n_Generated by AI-Ops Incident Dossier System_",
            proof_section
        )

        dossier_path.write_text(content, encoding="utf-8")

    def get_dossier(self, incident_id: str) -> Optional[str]:
        """Read and return dossier content."""
        dossier_path = self.incidents_dir / f"{incident_id}.md"
        if dossier_path.exists():
            return dossier_path.read_text(encoding="utf-8")
        return None
